### ISSUE TITLE
Everytime I start up the server, I receive this error. Happened with multiple fresh downloads.

### ISSUE THREAD

**Issue by Thebeast798** [Daribon/alpha-core_setup#1]
"sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'guild.realm_id' in 'field list'")

[SQL: SELECT guild.guild_id AS guild_guild_id, guild.realm_id AS guild_realm_id, [guild.name](https://guild.name/) AS guild_name, guild.motd AS guild_motd, guild.creation_date AS guild_creation_date, guild.emblem_style AS guild_emblem_style, guild.emblem_color AS guild_emblem_color, guild.border_style AS guild_border_style, guild.border_color AS guild_border_color, guild.background_color AS guild_background_color

FROM guild

WHERE guild.realm_id = %(realm_id_1)s]

[parameters: {'realm_id_1': 1}]"

**Comment by Daribon** [comment]
Uninstall mariaDB and pick delete data.
Once that is done use setup.bat and your issue will be resolved.
